#### Import Libraries

In [1]:
import streamlit as st

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score

#### Load Datasets

In [125]:
df_1 = pd.read_csv("dataset.csv")

print("Dataset shape is:", df_1.shape)

df_1.head()

Dataset shape is: (4920, 18)


Disease           Symptom_1           Symptom_2   Symptom_3 Symptom_4  \
0    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
1    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
2    Acne  pus_filled_pimples          blackheads    scurring       NaN   
3    Acne           skin_rash          blackheads    scurring       NaN   
4    Acne           skin_rash  pus_filled_pimples    scurring       NaN   

  Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11  \
0       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
1       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
2       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
3       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
4       NaN       NaN       NaN       NaN       NaN        NaN        NaN   

  Symptom_12 Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0        NaN        NaN        NaN        NaN        NaN        NaN  
1        NaN        NaN        NaN        NaN        NaN        NaN  
2        NaN        NaN        NaN        NaN        NaN        NaN  
3        NaN        NaN        NaN        NaN        NaN        NaN  
4        NaN        NaN        NaN        NaN        NaN        NaN

In [88]:
df_2 = pd.read_csv("symptom_Description.csv")

print("Description shape is:", df_2.shape)

df_2.head()

Description shape is: (41, 2)


Disease                                        Description
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [95]:
df_3 = pd.read_csv("symptom_precaution.csv")

print("Precaution shape is:", df_3.shape)
#df_3.fillna()
df_3.head()

Precaution shape is: (41, 5)


Disease                      Precaution_1  \
0   Drug Reaction                   stop irritation   
1         Malaria          Consult nearest hospital   
2         Allergy                    apply calamine   
3  Hypothyroidism                     reduce stress   
4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [122]:
"""A function that takes in a disease name , gives you a discription about the disease and precautions to take."""
def drug_info(disease):
    d = disease

    # Print disease description
    print("The predicted disease is:", d.strip().replace("_", " "))
    print(" ")
    print("Description of", d.strip().replace("_", " "),":")
    print(df_2[df_2["Disease"] == d]["Description"].item())
    print(" ")

    # Print Precautions to take
    print("Precautions to take are:")
    print(df_3[df_3["Disease"] == d]["Precaution_1"].item()) 
    print(df_3[df_3["Disease"] == d]["Precaution_2"].item())
    print(df_3[df_3["Disease"] == d]["Precaution_3"].item())
    print(df_3[df_3["Disease"] == d]["Precaution_4"].item())

In [123]:
drug_info("Malaria")

The predicted disease is: Malaria
 
Description of Malaria :
An infectious disease caused by protozoan parasites from the Plasmodium family that can be transmitted by the bite of the Anopheles mosquito or by a contaminated needle or transfusion. Falciparum malaria is the most deadly type.
 
Precautions to take are:
Consult nearest hospital
avoid oily food
avoid non veg food
keep mosquitos out


In [44]:
drug_info("Allergy")

An allergy is an immune system response to a foreign substance that's not typically harmful to your body.They can include certain foods, pollen, or pet dander. Your immune system's job is to keep you healthy by fighting harmful pathogens.
Precautions to take are:
apply calamine
cover area with bandage
nan
use ice to compress itching


In [9]:
df_4 = pd.read_csv("Symptom-severity.csv")

print("Severity shape is:", df_4.shape)

df_4.head()

Severity shape is: (133, 2)


Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [11]:
#convert data_severity to dictionnary
data_dict = df_4.set_index('Symptom').T.to_dict()

C:\Users\ThisPC\AppData\Local\Temp\ipykernel_17820\321082042.py:2: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  data_dict = df_4.set_index('Symptom').T.to_dict()


In [12]:
def remove_space_between_words(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].str.strip().str.replace(" ", "_")
    return df

In [126]:
df_1= remove_space_between_words(df_1)
df_1.head()

Disease           Symptom_1           Symptom_2   Symptom_3 Symptom_4  \
0    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
1    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
2    Acne  pus_filled_pimples          blackheads    scurring       NaN   
3    Acne           skin_rash          blackheads    scurring       NaN   
4    Acne           skin_rash  pus_filled_pimples    scurring       NaN   

  Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11  \
0       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
1       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
2       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
3       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
4       NaN       NaN       NaN       NaN       NaN        NaN        NaN   

  Symptom_12 Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0        NaN        NaN        NaN        NaN        NaN        NaN  
1        NaN        NaN        NaN        NaN        NaN        NaN  
2        NaN        NaN        NaN        NaN        NaN        NaN  
3        NaN        NaN        NaN        NaN        NaN        NaN  
4        NaN        NaN        NaN        NaN        NaN        NaN

In [56]:
symps = {"Symptom_1": "vomiting", "Symptom_2" : "skin_rash", "Symptom_3" : "itching","Symptom_4" : "nodal_skin_eruptions","Symptom_5" : np.nan,"Symptom_6" : np.nan,"Symptom_7" : np.nan,"Symptom_8" : np.nan,"Symptom_9" : np.nan,"Symptom_10" : np.nan,"Symptom_11" : np.nan, "Symptom_12" : np.nan,"Symptom_13" : np.nan,"Symptom_14" : np.nan,"Symptom_15" : np.nan, "Symptom_16" : np.nan,"Symptom_17" : np.nan,}

In [57]:
Test = pd.DataFrame(symps, index=range(1))
Test

Symptom_1  Symptom_2 Symptom_3             Symptom_4  Symptom_5  Symptom_6  \
0  vomiting  skin_rash   itching  nodal_skin_eruptions        NaN        NaN   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        NaN        NaN        NaN         NaN         NaN         NaN   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         NaN         NaN         NaN         NaN         NaN

In [17]:
def encode_symp(Test, df_4):
    for i in df_4.index:
        symptom = df_4["Symptom"][i]
        weight = df_4["weight"][i]
        Test = Test.replace(symptom, weight)
    
    # Replace missing values with 0
    Test = Test.fillna(0)

    # Additional hardcoded replacements
    Test = Test.replace("foul_smell_of_urine", 5)
    Test = Test.replace("dischromic__patches", 6)
    Test = Test.replace("spotting__urination", 6)
    return Test   

In [38]:
Test_01 = encode_symp(Test, df_4)
Test_01

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0          5          3          1        0.0        0.0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0

In [19]:
def encode_symptoms(df, df_4):
    for i in df_4.index:
        symptom = df_4["Symptom"][i]
        weight = df_4["weight"][i]
        df = df.replace(symptom, weight)

    # Replace missing values with 0
    df = df.fillna(0)

    # Additional hardcoded replacements
    df = df.replace("foul_smell_of_urine", 5)
    df = df.replace("dischromic__patches", 6)
    df = df.replace("spotting__urination", 6)
    
    return df

In [127]:
new_df_1 = encode_symptoms(df_1, df_4)
new_df_1.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0    Acne          3          2          2          2          0        0.0   
1    Acne          3          2          2          2          0        0.0   
2    Acne          2          2          2          0          0        0.0   
3    Acne          3          2          2          0          0        0.0   
4    Acne          3          2          2          0          0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   
1        0.0        0.0        0.0         0.0         0.0         0.0   
2        0.0        0.0        0.0         0.0         0.0         0.0   
3        0.0        0.0        0.0         0.0         0.0         0.0   
4        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0  
1         0.0         0.0         0.0         0.0         0.0  
2         0.0         0.0         0.0         0.0         0.0  
3         0.0         0.0         0.0         0.0         0.0  
4         0.0         0.0         0.0         0.0         0.0

In [69]:
new_df_1.describe()

Symptom_1    Symptom_2    Symptom_3    Symptom_4    Symptom_5  \
count  4920.000000  4920.000000  4920.000000  4920.000000  4920.000000   
mean      3.410976     4.165854     4.173171     3.967073     3.195122   
std       1.316310     1.207541     1.249229     1.855343     2.163883   
min       1.000000     2.000000     2.000000     0.000000     0.000000   
25%       3.000000     3.000000     3.000000     3.000000     2.000000   
50%       3.000000     4.000000     4.000000     4.000000     4.000000   
75%       4.000000     5.000000     5.000000     5.000000     5.000000   
max       7.000000     7.000000     7.000000     7.000000     7.000000   

         Symptom_6    Symptom_7    Symptom_8    Symptom_9   Symptom_10  \
count  4920.000000  4920.000000  4920.000000  4920.000000  4920.000000   
mean      2.654878     2.059756     1.712195     1.554878     1.304878   
std       2.384472     2.340259     2.244483     2.250034     2.061402   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       3.000000     0.000000     0.000000     0.000000     0.000000   
75%       5.000000     4.000000     4.000000     4.000000     3.000000   
max       7.000000     6.000000     7.000000     7.000000     6.000000   

        Symptom_11   Symptom_12   Symptom_13   Symptom_14   Symptom_15  \
count  4920.000000  4920.000000  4920.000000  4920.000000  4920.000000   
mean      0.979268     0.702439     0.492683     0.323171     0.282927   
std       1.880334     1.799707     1.529126     1.305543     1.298518   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       7.000000     7.000000     6.000000     7.000000     7.000000   

        Symptom_16   Symptom_17  
count  4920.000000  4920.000000  
mean      0.136585     0.029268  
std       0.719747     0.240191  
min       0.000000     0.000000  
25%       0.000000     0.000000  
50%       0.000000     0.000000  
75%       0.000000     0.000000  
max       5.000000     2.000000

In [21]:
names = []

# Iterate through columns except for "Disease"
for col in new_df_1.columns:
    if col != "Disease":
        # Iterate through rows in the column
        for symptom in new_df_1[col]:
            # Check if the value is a string and not in the 'names' list
            if isinstance(symptom, str) and symptom not in names:
                names.append(symptom)

# Check if all symptoms have been replaced
all_replaced = all(symptom not in names for symptom in df_4["Symptom"])

if all_replaced:
    print("All symptoms have been replaced.")
else:
    print("The following symptoms were not replaced:", names)

All symptoms have been replaced.


In [128]:
# separating the data and labels
X = new_df_1.drop(columns='Disease', axis=1)
Y = new_df_1['Disease']

In [129]:
X.head()

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0          3          2          2          2          0        0.0   
1          3          2          2          2          0        0.0   
2          2          2          2          0          0        0.0   
3          3          2          2          0          0        0.0   
4          3          2          2          0          0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   
1        0.0        0.0        0.0         0.0         0.0         0.0   
2        0.0        0.0        0.0         0.0         0.0         0.0   
3        0.0        0.0        0.0         0.0         0.0         0.0   
4        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0  
1         0.0         0.0         0.0         0.0         0.0  
2         0.0         0.0         0.0         0.0         0.0  
3         0.0         0.0         0.0         0.0         0.0  
4         0.0         0.0         0.0         0.0         0.0

### Data Standardization

In [25]:
scaler = StandardScaler()

In [130]:
scaler.fit(X)

StandardScaler()

In [131]:
standardized_data = scaler.transform(X)

In [28]:
#print(standardized_data)

In [132]:
X = standardized_data
Y = new_df_1['Disease']

In [30]:
#print(X)

In [31]:
#print(Y)

####  Random Forest Classifier

In [133]:
from sklearn.ensemble import RandomForestClassifier
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Create a Random Forest Classifier
rfc_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model on the training data
rfc_classifier.fit(X_train, Y_train)

# Predict disease labels on the testing data
Y_pred = rfc_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(Y_test, Y_pred)

precision = precision_score(Y_test, Y_pred, average='macro')
recall = recall_score(Y_test, Y_pred,average='macro')
f1 = f1_score(Y_test, Y_pred, average='macro')

print("Random Forest")
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-Score: {f1}')
print(accuracy_score(Y_test, Y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(Y_test,Y_pred)
print(conf_matrix)

Random Forest
Accuracy: 0.9908536585365854
Precision: 0.9916531165311654
Recall: 0.9918172648227722
F1-Score: 0.9914105369307706
975
Confusion matrix
[[31  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 21 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 24]]


#### Create Model that predicts disease and returns information about the disease

In [134]:
Test_01

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0          5          3          1        0.0        0.0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0

In [136]:
standardized_test = scaler.transform(Test_01)
standardized_test

array([[ 1.20730412, -0.96557578, -2.54036159, -2.13840565, -1.47671853,
        -1.11351624, -0.88022981, -0.7629236 , -0.69111681, -0.6330696 ,
        -0.52084789, -0.39034712, -0.32223177, -0.24756248, -0.21790657,
        -0.18978799, -0.12186667]])

In [135]:
d = rfc_classifier.predict(standardized_test).item()
d = d.strip().replace(" ", "_")
print(d)

Paralysis_(brain_hemorrhage)


In [137]:
drug_info(d)

The predicted disease is: Paralysis (brain hemorrhage)
 
Description of Paralysis (brain hemorrhage) :
Intracerebral hemorrhage (ICH) is when blood suddenly bursts into brain tissue, causing damage to your brain. Symptoms usually appear suddenly during ICH. They include headache, weakness, confusion, and paralysis, particularly on one side of your body.
 
Precautions to take are:
massage
eat healthy
exercise
consult doctor
