#### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder
import streamlit as st
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import SparseCategoricalCrossentropy


In [13]:
"""
A function that takes in symptoms and creates a dataframe ready for prediction
"""
def dataframe(dic):
    #dic= {"Symptom_1":symp}
    df = pd.DataFrame(dic, index=[0])
    return df


In [20]:
sympt = {"Symptom_1": "rash", "Symptom_2":" vomiting", "Symptom_3": "headache","Symptom_4" : "nodal_skin_eruptions","Symptom_5" : np.nan,"Symptom_6" : np.nan,"Symptom_7" : np.nan,"Symptom_8" : np.nan,"Symptom_9" : np.nan,"Symptom_10" : np.nan,"Symptom_11" : np.nan, "Symptom_12" : np.nan,"Symptom_13" : np.nan,"Symptom_14" : np.nan,"Symptom_15" : np.nan, "Symptom_16" : np.nan,"Symptom_17" : np.nan}

In [21]:
dataframe(sympt)

Symptom_1  Symptom_2 Symptom_3             Symptom_4  Symptom_5  Symptom_6  \
0      rash   vomiting  headache  nodal_skin_eruptions        NaN        NaN   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        NaN        NaN        NaN         NaN         NaN         NaN   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         NaN         NaN         NaN         NaN         NaN

In [56]:
symps = {"Symptom_1": "vomiting", "Symptom_2" : "skin_rash", "Symptom_3" : "itching","Symptom_4" : "nodal_skin_eruptions","Symptom_5" : np.nan,"Symptom_6" : np.nan,"Symptom_7" : np.nan,"Symptom_8" : np.nan,"Symptom_9" : np.nan,"Symptom_10" : np.nan,"Symptom_11" : np.nan, "Symptom_12" : np.nan,"Symptom_13" : np.nan,"Symptom_14" : np.nan,"Symptom_15" : np.nan, "Symptom_16" : np.nan,"Symptom_17" : np.nan,}

In [57]:
Test = pd.DataFrame(symps, index=range(1))
Test

Symptom_1  Symptom_2 Symptom_3             Symptom_4  Symptom_5  Symptom_6  \
0  vomiting  skin_rash   itching  nodal_skin_eruptions        NaN        NaN   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        NaN        NaN        NaN         NaN         NaN         NaN   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         NaN         NaN         NaN         NaN         NaN

#### Load Datasets

In [2]:
df_1 = pd.read_csv("dataset.csv")

print("Dataset shape is:", df_1.shape)

df_1.head()

Dataset shape is: (4920, 18)


Disease           Symptom_1           Symptom_2   Symptom_3 Symptom_4  \
0    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
1    Acne           skin_rash  pus_filled_pimples  blackheads  scurring   
2    Acne  pus_filled_pimples          blackheads    scurring       NaN   
3    Acne           skin_rash          blackheads    scurring       NaN   
4    Acne           skin_rash  pus_filled_pimples    scurring       NaN   

  Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11  \
0       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
1       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
2       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
3       NaN       NaN       NaN       NaN       NaN        NaN        NaN   
4       NaN       NaN       NaN       NaN       NaN        NaN        NaN   

  Symptom_12 Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0        NaN        NaN        NaN        NaN        NaN        NaN  
1        NaN        NaN        NaN        NaN        NaN        NaN  
2        NaN        NaN        NaN        NaN        NaN        NaN  
3        NaN        NaN        NaN        NaN        NaN        NaN  
4        NaN        NaN        NaN        NaN        NaN        NaN

In [97]:
def uniq_symp(df):
    a = df["Symptom_1"].unique().tolist()
    b = df["Symptom_2"].unique().tolist()
    c = df["Symptom_3"].unique().tolist()
    d = df["Symptom_4"].unique().tolist()
    e = df["Symptom_5"].unique().tolist()
    f = df["Symptom_6"].unique().tolist()
    g = df["Symptom_7"].unique().tolist()
    h = df["Symptom_8"].unique().tolist()
    i = df["Symptom_9"].unique().tolist()
    j = df["Symptom_10"].unique().tolist()
    k = df["Symptom_11"].unique().tolist()
    l = df["Symptom_12"].unique().tolist()
    m= df["Symptom_13"].unique().tolist()
    n = df["Symptom_14"].unique().tolist()
    o = df["Symptom_15"].unique().tolist()
    p = df["Symptom_16"].unique().tolist()
    q= df["Symptom_17"].unique().tolist()



    z = a+b+c+d+e+f+g+h+i+j+k+l+m+o+p+q
    symp = {"Symptoms": z}
    df = pd.DataFrame(symp, index=range(len(z)))
    uniq = df["Symptoms"].unique().tolist()

    return uniq

In [107]:
sym = ['skin_rash', 'pus_filled_pimples', 'muscle_wasting', 'patches_in_throat', 'vomiting', 'yellowish_skin','continuous_sneezing', 'shivering', 'muscle_weakness','stiff_neck', 'fatigue', 'cough', 'back_pain', 'weakness_in_limbs', 'itching', 'chills', 'weight_loss', 'constipation', 'pain_during_bowel_movements', 'sunken_eyes', 'stomach_pain','acidity', 'breathlessness', 'joint_pain', 'headache','chest_pain', 'mood_swings', 'weight_gain', 'high_fever','indigestion', 'neck_pain', 'burning_micturition', 'bladder_discomfort', 'cramps', 'blackheads', 'abdominal_pain', 'swelling_joints', 'restlessness', 'pain_in_anal_region','nodal_skin_eruptions', 'dehydration', 'ulcers_on_tongue', 'sweating', 'lethargy', 'nausea', 'dizziness', 'anxiety', 'cold_hands_and_feets', 'blister', 'knee_pain','weakness_of_one_body_side', 'loss_of_appetite', 'skin_peeling','foul_smell_of_urine', 'bruising', 'scurring', 'extra_marital_contacts', 'swelling_of_stomach','watering_from_eyes', 'movement_stiffness', 'bloody_stool', 'dischromic__patches', 'diarrhoea', 'dark_urine', 'loss_of_balance', 'red_sore_around_nose','blurred_and_distorted_vision', 'hip_joint_pain','altered_sensorium', 'spinning_movements', 'silver_like_dusting', 'continuous_feel_of_urine', 'obesity', 'distention_of_abdomen', 'painful_walking', 'family_history', 'irregular_sugar_level', 'irritation_in_anus', 'spotting__urination', 'yellowing_of_eyes', 'lack_of_concentration', 'yellow_crust_ooze', 'excessive_hunger','passage_of_gases', 'small_dents_in_nails', 'swollen_legs','history_of_alcohol_consumption', 'mucoid_sputum', 'unsteadiness','internal_itching', 'inflammatory_nails', 'swollen_blood_vessels', 'fluid_overload', 'swelled_lymph_nodes', 'fast_heart_rate', 'puffy_face_and_eyes', 'depression', 'malaise','prominent_veins_on_calf', 'mild_fever', 'yellow_urine','enlarged_thyroid', 'muscle_pain', 'irritability', 'phlegm','increased_appetite', 'drying_and_tingling_lips', 'brittle_nails','visual_disturbances', 'throat_irritation', 'pain_behind_the_eyes','polyuria', 'slurred_speech', 'swollen_extremeties', 'toxic_look_(typhos)', 'red_spots_over_body', 'redness_of_eyes', 'receiving_blood_transfusion', 'acute_liver_failure', 'abnormal_menstruation', 'rusty_sputum', 'belly_pain', 'sinus_pressure', 'receiving_unsterile_injections', 'coma', 'palpitations', 'runny_nose', 'stomach_bleeding', 'congestion',  'loss_of_smell', 'blood_in_sputum']

In [110]:
v = sorted(sym)
v

['abdominal_pain',
 'abnormal_menstruation',
 'acidity',
 'acute_liver_failure',
 'altered_sensorium',
 'anxiety',
 'back_pain',
 'belly_pain',
 'blackheads',
 'bladder_discomfort',
 'blister',
 'blood_in_sputum',
 'bloody_stool',
 'blurred_and_distorted_vision',
 'breathlessness',
 'brittle_nails',
 'bruising',
 'burning_micturition',
 'chest_pain',
 'chills',
 'cold_hands_and_feets',
 'coma',
 'congestion',
 'constipation',
 'continuous_feel_of_urine',
 'continuous_sneezing',
 'cough',
 'cramps',
 'dark_urine',
 'dehydration',
 'depression',
 'diarrhoea',
 'dischromic__patches',
 'distention_of_abdomen',
 'dizziness',
 'drying_and_tingling_lips',
 'enlarged_thyroid',
 'excessive_hunger',
 'extra_marital_contacts',
 'family_history',
 'fast_heart_rate',
 'fatigue',
 'fluid_overload',
 'foul_smell_of_urine',
 'headache',
 'high_fever',
 'hip_joint_pain',
 'history_of_alcohol_consumption',
 'increased_appetite',
 'indigestion',
 'inflammatory_nails',
 'internal_itching',
 'irregular_sug

In [106]:
uniq_symp(df_1)




['skin_rash',
 'pus_filled_pimples',
 'muscle_wasting',
 'patches_in_throat',
 'vomiting',
 'yellowish_skin',
 'continuous_sneezing',
 'shivering',
 'muscle_weakness',
 'stiff_neck',
 'fatigue',
 'cough',
 'back_pain',
 'weakness_in_limbs',
 'itching',
 'chills',
 'weight_loss',
 'constipation',
 'pain_during_bowel_movements',
 'sunken_eyes',
 'stomach_pain',
 'acidity',
 'breathlessness',
 'joint_pain',
 'headache',
 'chest_pain',
 'mood_swings',
 'weight_gain',
 'high_fever',
 'indigestion',
 'neck_pain',
 'burning_micturition',
 'bladder_discomfort',
 'cramps',
 'blackheads',
 'abdominal_pain',
 'swelling_joints',
 'restlessness',
 'pain_in_anal_region',
 'nodal_skin_eruptions',
 'dehydration',
 'ulcers_on_tongue',
 'sweating',
 'lethargy',
 'nausea',
 'dizziness',
 'anxiety',
 'cold_hands_and_feets',
 'blister',
 'knee_pain',
 'weakness_of_one_body_side',
 'loss_of_appetite',
 'skin_peeling',
 'foul_smell_of_urine',
 'bruising',
 'scurring',
 'extra_marital_contacts',
 'swelling_of

In [ ]:
'abdominal_pain','abnormal_menstruation','acidity','acute_liver_failure','altered_sensorium', 'anxiety','back_pain','belly_pain','blackheads','bladder_discomfort','blister','blood_in_sputum','bloody_stool','blurred_and_distorted_vision','breathlessness','brittle_nails','bruising','burning_micturition','chest_pain','chills', 'cold_hands_and_feets','coma','congestion','constipation','continuous_feel_of_urine','continuous_sneezing','cough','cramps','dark_urine','dehydration','depression', 'diarrhoea','dischromic__patches','distention_of_abdomen','dizziness','drying_and_tingling_lips','enlarged_thyroid','excessive_hunger','extra_marital_contacts','family_history', 'fast_heart_rate','fatigue', 'fluid_overload','foul_smell_of_urine','headache','high_fever','hip_joint_pain', 'history_of_alcohol_consumption','increased_appetite','indigestion','inflammatory_nails','internal_itching','irregular_sugar_level','irritability','irritation_in_anus','itching','joint_pain','knee_pain','lack_of_concentration', 'lethargy','loss_of_appetite','loss_of_balance', 'loss_of_smell','malaise','mild_fever','mood_swings','movement_stiffness', 'mucoid_sputum','muscle_pain','muscle_wasting','muscle_weakness','nausea','neck_pain','nodal_skin_eruptions','obesity','pain_behind_the_eyes','pain_during_bowel_movements','pain_in_anal_region','painful_walking','palpitations','passage_of_gases','patches_in_throat','phlegm','polyuria','prominent_veins_on_calf','puffy_face_and_eyes','pus_filled_pimples','receiving_blood_transfusion','receiving_unsterile_injections','red_sore_around_nose','red_spots_over_body','redness_of_eyes','restlessness','runny_nose','rusty_sputum','scurring','shivering','silver_like_dusting','sinus_pressure','skin_peeling','skin_rash','slurred_speech','small_dents_in_nails','spinning_movements','spotting__urination','stiff_neck','stomach_bleeding','stomach_pain','sunken_eyes','sweating','swelled_lymph_nodes','swelling_joints','swelling_of_stomach','swollen_blood_vessels','swollen_extremeties','swollen_legs','throat_irritation','toxic_look_(typhos)','ulcers_on_tongue','unsteadiness','visual_disturbances','vomiting','watering_from_eyes','weakness_in_limbs','weakness_of_one_body_side','weight_gain','weight_loss','yellow_crust_ooze','yellow_urine','yellowing_of_eyes','yellowish_skin'

In [54]:
a = df_1["Symptom_1"].unique().tolist()

In [53]:
b = df_1["Symptom_2"].unique().tolist()


In [87]:
c = a+b
symp = {"Symptoms": c}
df = pd.DataFrame(symp, index=range(len(c)))
df["Symptoms"].unique()


array(['skin_rash', 'pus_filled_pimples', 'muscle_wasting',
       'patches_in_throat', 'vomiting', 'yellowish_skin',
       'continuous_sneezing', 'shivering', 'muscle_weakness',
       'stiff_neck', 'fatigue', 'cough', 'back_pain', 'weakness_in_limbs',
       'itching', 'chills', 'weight_loss', 'constipation',
       'pain_during_bowel_movements', 'sunken_eyes', 'stomach_pain',
       'acidity', 'breathlessness', 'joint_pain', 'headache',
       'chest_pain', 'mood_swings', 'weight_gain', 'high_fever',
       'indigestion', 'neck_pain', 'burning_micturition',
       'bladder_discomfort', 'cramps', 'blackheads', 'abdominal_pain',
       'swelling_joints', 'restlessness', 'pain_in_anal_region',
       'nodal_skin_eruptions', 'dehydration', 'ulcers_on_tongue',
       'sweating', 'lethargy', 'nausea', 'dizziness', 'anxiety',
       'cold_hands_and_feets', 'blister', 'knee_pain',
       'weakness_of_one_body_side', 'loss_of_appetite', 'skin_peeling',
       'foul_smell_of_urine', 'bruisin

In [79]:
c = a+b

In [60]:
len(c)

82

In [63]:
symp = {"Symptomps": c}

In [66]:
symp = {"Symptoms": c}
df = pd.DataFrame(symp, index=range(len(c)))
df.head()

Symptoms
0           skin_rash
1  pus_filled_pimples
2      muscle_wasting
3   patches_in_throat
4            vomiting

In [3]:
df_2 = pd.read_csv("symptom_Description.csv")

print("Description shape is:", df_2.shape)

df_2.head()

Description shape is: (41, 2)


Disease                                        Description
0   Drug_Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [5]:
df_2[df_2["Disease"] == "Heart_attack"]["Description"].item()

'The death of heart muscle due to the loss of blood supply. The loss of blood supply is usually caused by a complete blockage of a coronary artery, one of the arteries that supplies blood to the heart muscle.'

In [4]:
df_3 = pd.read_csv("symptom_precaution.csv")

print("Precaution shape is:", df_3.shape)
#df_3.fillna()
df_3.head()

Precaution shape is: (41, 5)


Disease                      Precaution_1  \
0   Drug_Reaction                   stop irritation   
1         Malaria          Consult nearest hospital   
2         Allergy                    apply calamine   
3  Hypothyroidism                     reduce stress   
4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2                 Precaution_3  \
0      consult nearest hospital             stop taking drug   
1               avoid oily food           avoid non veg food   
2       cover area with bandage  use ice to compress itching   
3                      exercise                  eat healthy   
4  stop bleeding using pressure               consult doctor   

               Precaution_4  
0                 follow up  
1        keep mosquitos out  
2  know and avoid allergens  
3          get proper sleep  
4                salt baths

In [13]:
"""A function that takes in a disease name , gives you a discription about the disease and precautions to take."""
def drug_info(disease):
    d = disease

    # Print disease description
    print("The predicted disease is:", d.strip().replace("_", " "))
    print(" ")
    print("Description of", d.strip().replace("_", " "),":")
    print(df_2[df_2["Disease"] == d]["Description"].item())
    print(" ")

    # Print Precautions to take
    print("Precautions to take are:")
    print(df_3[df_3["Disease"] == d]["Precaution_1"].item().title()) 
    print(df_3[df_3["Disease"] == d]["Precaution_2"].item().title())
    print(df_3[df_3["Disease"] == d]["Precaution_3"].item().title())
    print(df_3[df_3["Disease"] == d]["Precaution_4"].item().title())

In [14]:
drug_info("Malaria")

The predicted disease is: Malaria
 
Description of Malaria :
An infectious disease caused by protozoan parasites from the Plasmodium family that can be transmitted by the bite of the Anopheles mosquito or by a contaminated needle or transfusion. Falciparum malaria is the most deadly type.
 
Precautions to take are:
Consult Nearest Hospital
Avoid Oily Food
Avoid Non Veg Food
Keep Mosquitos Out


In [16]:
#drug_info("Allergy")

In [18]:
df_4 = pd.read_csv("Symptom-severity.csv")

print("Severity shape is:", df_4.shape)

df_4.head()

Severity shape is: (133, 2)


Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [19]:
#convert data_severity to dictionnary
data_dict = df_4.set_index('Symptom').T.to_dict()

C:\Users\ThisPC\AppData\Local\Temp\ipykernel_4832\321082042.py:2: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  data_dict = df_4.set_index('Symptom').T.to_dict()


In [20]:
def remove_space_between_words(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].str.strip().str.replace(" ", "_")
    return df

In [29]:
df_1= remove_space_between_words(df_1)
df_1.to_csv("dataset.csv")

In [22]:
def encode_symp(Test, df_4):
    for i in df_4.index:
        symptom = df_4["Symptom"][i]
        weight = df_4["weight"][i]
        Test = Test.replace(symptom, weight)
    
    # Replace missing values with 0
    Test = Test.fillna(0)

    # Additional hardcoded replacements
    Test = Test.replace("foul_smell_of_urine", 5)
    Test = Test.replace("dischromic__patches", 6)
    Test = Test.replace("spotting__urination", 6)
    return Test   

In [24]:
#Test_01 = encode_symp(Test, df_4)
#Test_01

In [25]:
def encode_symptoms(df, df_4):
    for i in df_4.index:
        symptom = df_4["Symptom"][i]
        weight = df_4["weight"][i]
        df = df.replace(symptom, weight)

    # Replace missing values with 0
    df = df.fillna(0)

    # Additional hardcoded replacements
    df = df.replace("foul_smell_of_urine", 5)
    df = df.replace("dischromic__patches", 6)
    df = df.replace("spotting__urination", 6)
    
    return df

In [26]:
new_df_1 = encode_symptoms(df_1, df_4)
new_df_1.head()

Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0    Acne          3          2          2          2          0        0.0   
1    Acne          3          2          2          2          0        0.0   
2    Acne          2          2          2          0          0        0.0   
3    Acne          3          2          2          0          0        0.0   
4    Acne          3          2          2          0          0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   
1        0.0        0.0        0.0         0.0         0.0         0.0   
2        0.0        0.0        0.0         0.0         0.0         0.0   
3        0.0        0.0        0.0         0.0         0.0         0.0   
4        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0  
1         0.0         0.0         0.0         0.0         0.0  
2         0.0         0.0         0.0         0.0         0.0  
3         0.0         0.0         0.0         0.0         0.0  
4         0.0         0.0         0.0         0.0         0.0

In [27]:
#new_df_1.describe()

In [34]:
names = []

# Iterate through columns except for "Disease"
for col in new_df_1.columns:
    if col != "Disease":
        # Iterate through rows in the column
        for symptom in new_df_1[col]:
            # Check if the value is a string and not in the 'names' list
            if isinstance(symptom, str) and symptom not in names:
                names.append(symptom)

# Check if all symptoms have been replaced
all_replaced = all(symptom not in names for symptom in df_4["Symptom"])

if all_replaced:
    print("All symptoms have been replaced.")
else:
    print("The following symptoms were not replaced:", names)

All symptoms have been replaced.


In [128]:
# separating the data and labels
X = new_df_1.drop(columns='Disease', axis=1)
Y = new_df_1['Disease']

In [129]:
X.head()

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0          3          2          2          2          0        0.0   
1          3          2          2          2          0        0.0   
2          2          2          2          0          0        0.0   
3          3          2          2          0          0        0.0   
4          3          2          2          0          0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   
1        0.0        0.0        0.0         0.0         0.0         0.0   
2        0.0        0.0        0.0         0.0         0.0         0.0   
3        0.0        0.0        0.0         0.0         0.0         0.0   
4        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0  
1         0.0         0.0         0.0         0.0         0.0  
2         0.0         0.0         0.0         0.0         0.0  
3         0.0         0.0         0.0         0.0         0.0  
4         0.0         0.0         0.0         0.0         0.0

### Data Standardization

In [25]:
scaler = StandardScaler()

In [130]:
scaler.fit(X)

StandardScaler()

In [131]:
standardized_data = scaler.transform(X)

In [28]:
#print(standardized_data)

In [132]:
X = standardized_data
Y = new_df_1['Disease']

In [30]:
#print(X)

In [31]:
#print(Y)

####  Random Forest Classifier

In [133]:
from sklearn.ensemble import RandomForestClassifier
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Create a Random Forest Classifier
rfc_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model on the training data
rfc_classifier.fit(X_train, Y_train)

# Predict disease labels on the testing data
Y_pred = rfc_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(Y_test, Y_pred)

precision = precision_score(Y_test, Y_pred, average='macro')
recall = recall_score(Y_test, Y_pred,average='macro')
f1 = f1_score(Y_test, Y_pred, average='macro')

print("Random Forest")
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-Score: {f1}')
print(accuracy_score(Y_test, Y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(Y_test,Y_pred)
print(conf_matrix)

Random Forest
Accuracy: 0.9908536585365854
Precision: 0.9916531165311654
Recall: 0.9918172648227722
F1-Score: 0.9914105369307706
975
Confusion matrix
[[31  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 21 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 24]]


#### Create Model that predicts disease and returns information about the disease

In [134]:
Test_01

Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  Symptom_6  \
0          5          3          1        0.0        0.0        0.0   

   Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  Symptom_12  \
0        0.0        0.0        0.0         0.0         0.0         0.0   

   Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0         0.0         0.0         0.0         0.0         0.0

In [136]:
standardized_test = scaler.transform(Test_01)
standardized_test

array([[ 1.20730412, -0.96557578, -2.54036159, -2.13840565, -1.47671853,
        -1.11351624, -0.88022981, -0.7629236 , -0.69111681, -0.6330696 ,
        -0.52084789, -0.39034712, -0.32223177, -0.24756248, -0.21790657,
        -0.18978799, -0.12186667]])

In [36]:
d = rfc_classifier.predict(standardized_test).item()
d = d.strip().replace(" ", "_")
print(d)

NameError: name 'rfc_classifier' is not defined

In [35]:
drug_info(d)

NameError: name 'd' is not defined